// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqS6gKDkjseLPaaKxV2J7HO5-OslCfR9w',
    appId: '1:179831856277:web:a293788ab14aedb60e4f9c',
    messagingSenderId: '179831856277',
    projectId: 'citideals',
    authDomain: 'citideals.firebaseapp.com',
    storageBucket: 'citideals.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANs2NYhDbIz1hufzDLsfVxfY_ildwmj8s',
    appId: '1:179831856277:android:6d6086a23f57c8140e4f9c',
    messagingSenderId: '179831856277',
    projectId: 'citideals',
    storageBucket: 'citideals.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ3tl6dXpfRYtVhnOBky8fRz299usiepY',
    appId: '1:179831856277:ios:e8ca29be50a3aae40e4f9c',
    messagingSenderId: '179831856277',
    projectId: 'citideals',
    storageBucket: 'citideals.firebasestorage.app',
    iosBundleId: 'com.citideals.citideals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZ3tl6dXpfRYtVhnOBky8fRz299usiepY',
    appId: '1:179831856277:ios:e8ca29be50a3aae40e4f9c',
    messagingSenderId: '179831856277',
    projectId: 'citideals',
    storageBucket: 'citideals.firebasestorage.app',
    iosBundleId: 'com.citideals.citideals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqS6gKDkjseLPaaKxV2J7HO5-OslCfR9w',
    appId: '1:179831856277:web:e9bc9a4cf43cf1fa0e4f9c',
    messagingSenderId: '179831856277',
    projectId: 'citideals',
    authDomain: 'citideals.firebaseapp.com',
    storageBucket: 'citideals.firebasestorage.app',
  );
}
